# Generated by Django 4.2.6 on 2023-11-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_alter_profile_phone_number_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images'),
        ),
    ]
